// Data
export const GET_DATA = 'GET_DATA'
export const UPDATE_OR_CREATE_DATA = 'UPDATE_OR_CREATE_DATA'

// Auth
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGOUT = 'LOGOUT'

// Meetings
export const CLEAR_MEETINGS = 'CLEAR_MEETINGS'
export const ADD_LOADED_DATES = 'ADD_LOADED_DATES'
export const LOAD_BARBERS = 'LOAD_BARBERS'
export const LOAD_CUSTOMERS = 'LOAD_CUSTOMERS'

export const MEETINGS_LOADING = 'MEETINGS_LOADING'
export const MEETINGS_CONNECT_WS = 'MEETINGS_CONNECT_WS'
export const LOAD_MEETINGS = 'LOAD_MEETINGS'
export const ADD_MEETING = 'ADD_MEETING'
export const REMOVE_MEETING = 'REMOVE_MEETING'
