# Generated by Django 3.1.7 on 2021-03-27 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0003_auto_20210327_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Konto Klienta'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(verbose_name='Wizyta jest o'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('hair', 'Włosy'), ('beard', 'Broda')], max_length=5, verbose_name='Typ Wizyty'),
        ),
    ]
