# Generated by Django 3.1.7 on 2021-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20210327_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(unique=True, verbose_name='Wizyta jest o'),
        ),
    ]
