# Generated by Django 3.1.7 on 2021-04-04 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20210403_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Kończy się o'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(verbose_name='Zaczyna się o'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('hair', 'Włosy'), ('beard', 'Broda'), ('do_not_work', 'NIE PRACUJE')], max_length=11, verbose_name='Typ Wizyty'),
        ),
    ]
