# Generated by Django 3.1.7 on 2021-04-15 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0007_auto_20210404_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='barber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Fryzjer'),
            preserve_default=False,
        ),
    ]
