# Generated by Django 3.1.7 on 2021-04-19 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0010_auto_20210419_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Fryzjer'),
        ),
    ]
