# Generated by Django 3.1.7 on 2021-05-11 11:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20210419_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Imię klienta'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nazwisko klienta'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='customer_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Numer telefonu klienta'),
        ),
    ]
