# Generated by Django 3.1.7 on 2021-05-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_auto_20210511_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
