# Generated by Django 3.1.7 on 2021-05-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210521_1716'),
        ('meetings', '0013_meeting_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.barber', verbose_name='Fryzjer'),
        ),
    ]
