# Generated by Django 3.1.7 on 2021-05-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20210523_1429'),
        ('meetings', '0014_auto_20210521_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='type',
        ),
        migrations.AddField(
            model_name='meeting',
            name='do_not_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='service',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='data.service'),
            preserve_default=False,
        ),
    ]
