# Generated by Django 3.1.7 on 2021-05-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20210523_1429'),
        ('meetings', '0015_auto_20210523_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='data.service'),
        ),
    ]
