# Generated by Django 3.1.7 on 2021-06-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210615_1704'),
        ('data', '0034_serviceimage'),
        ('meetings', '0017_meeting_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='customer_fax_number',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='customer_first_name',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='customer_last_name',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='customer_phone_number',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='do_not_work',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.barber', verbose_name='Fryzjer'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.customer', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end',
            field=models.DateTimeField(verbose_name='Kończy się o'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='data.service'),
        ),
    ]
