# Generated by Django 3.1.7 on 2021-06-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210615_1704'),
        ('data', '0034_serviceimage'),
        ('meetings', '0018_auto_20210615_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='service',
        ),
        migrations.AddField(
            model_name='meeting',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='data.Service'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.customer', verbose_name='Klient'),
        ),
    ]
