# Generated by Django 3.1.7 on 2021-06-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0019_auto_20210615_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='services',
        ),
    ]
