# Generated by Django 3.1.7 on 2021-06-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_serviceimage'),
        ('accounts', '0017_auto_20210615_1704'),
        ('meetings', '0020_remove_meeting_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_data', to='accounts.barber')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_data', to='meetings.meeting')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_data', to='data.service')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='meetings', through='meetings.ServiceData', to='data.Service'),
        ),
    ]
