# Generated by Django 3.1.7 on 2021-06-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210615_1704'),
        ('meetings', '0021_auto_20210619_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.barber', verbose_name='Fryzjer'),
        ),
    ]
