# Generated by Django 3.1.7 on 2021-06-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_auto_20210624_1437'),
        ('meetings', '0022_auto_20210619_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='data.Resource'),
        ),
    ]
