# Generated by Django 3.1.7 on 2021-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_auto_20210625_1801'),
        ('meetings', '0023_meeting_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedata',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='services_data', to='data.Resource'),
        ),
    ]
