# Generated by Django 3.1.7 on 2021-06-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0024_servicedata_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='resources',
        ),
    ]
