# Generated by Django 3.1.7 on 2021-07-04 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0026_auto_20210628_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedata',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kończy się o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicedata',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zaczyna się o'),
            preserve_default=False,
        ),
    ]
