# Generated by Django 3.1.7 on 2021-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210419_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trusted_customer',
            field=models.BooleanField(default=False),
        ),
    ]
