# Generated by Django 3.1.7 on 2021-04-30 14:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_trusted_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='first_name', unique=True),
        ),
    ]
