# Generated by Django 3.1.7 on 2021-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210512_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='revenue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
