# Generated by Django 3.1.7 on 2021-05-21 14:32

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210513_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=20, verbose_name='Nazwisko')),
                ('color', models.CharField(default='212121', max_length=6)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='first_name', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='account',
            name='color',
        ),
        migrations.RemoveField(
            model_name='account',
            name='no_shows',
        ),
        migrations.RemoveField(
            model_name='account',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='account',
            name='trusted_customer',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('no_shows', models.PositiveIntegerField(default=0)),
                ('revenue', models.PositiveIntegerField(default=0)),
                ('trusted', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
