# Generated by Django 3.1.7 on 2021-05-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210521_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Barber',
        ),
    ]
