# Generated by Django 3.1.7 on 2021-05-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210521_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='color',
            field=models.CharField(choices=[('Czarny', 'black'), ('Jasny niebieski', 'light-blue'), ('Niebieski', 'blue'), ('Jasny Zielony', 'light-green'), ('Zielony', 'green'), ('Różowy', 'pink'), ('Fioletowy', 'purple'), ('Brązowy', 'brown'), ('Żółty', 'yellow'), ('Pomarańczowy', 'orange')], default='black', max_length=15),
        ),
    ]
