# Generated by Django 3.1.7 on 2021-05-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210527_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='color',
            field=models.CharField(choices=[('black', 'Czarny'), ('light-blue', 'Jasny niebieski'), ('blue', 'Niebieski'), ('light-green', 'Jasny Zielony'), ('green', 'Zielony'), ('pink', 'Różowy'), ('purple', 'Fioletowy'), ('brown', 'Brązowy'), ('yellow', 'Żółty'), ('orange', 'Pomarańczowy')], default='Czarny', max_length=15),
        ),
    ]
