# Generated by Django 3.1.7 on 2021-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='value',
            field=models.CharField(default='123 123 123', max_length=100),
            preserve_default=False,
        ),
    ]
