# Generated by Django 3.1.7 on 2021-04-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210404_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='display_name',
            field=models.CharField(default='xd', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
