# Generated by Django 3.1.7 on 2021-04-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210404_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
