# Generated by Django 3.1.7 on 2021-04-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210422_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='display_name',
        ),
    ]
