# Generated by Django 3.1.7 on 2021-05-06 14:03

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_data_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
        migrations.AddField(
            model_name='data',
            name='beard_price',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=4),
        ),
        migrations.AddField(
            model_name='data',
            name='contact_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='data',
            name='contact_content_second',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='data',
            name='contact_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='end_work_friday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='end_work_monday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='end_work_saturday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='end_work_sunday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='end_work_thursday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='end_work_tuesday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='end_work_wednesday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='free_cancel_hours',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='data',
            name='gallery_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='data',
            name='gallery_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='data',
            name='hair_price',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=4),
        ),
        migrations.AddField(
            model_name='data',
            name='home_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='data',
            name='home_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='meeting_bail',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
        migrations.AddField(
            model_name='data',
            name='meeting_prepayment',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=4),
        ),
        migrations.AddField(
            model_name='data',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='data',
            name='start_work_friday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='start_work_monday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='start_work_saturday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='start_work_sunday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='start_work_thursday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='start_work_tuesday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='start_work_wednesday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='work_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
