# Generated by Django 3.1.7 on 2021-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210506_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='end_work_friday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_work_monday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_work_saturday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_work_sunday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_work_thursday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_work_tuesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_work_wednesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_work_friday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_work_monday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_work_saturday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_work_sunday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_work_thursday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_work_tuesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_work_wednesday',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
