# Generated by Django 3.1.7 on 2021-05-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20210506_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='work_time',
        ),
    ]
