# Generated by Django 3.1.7 on 2021-05-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_data_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='work_time',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
