# Generated by Django 3.1.7 on 2021-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_data_one_slot_max_meetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
