# Generated by Django 3.1.7 on 2021-05-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20210516_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reciver',
            new_name='recivers',
        ),
    ]
