# Generated by Django 3.1.7 on 2021-05-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_notification_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='one_slot_max_meetings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
