# Generated by Django 3.1.7 on 2021-05-21 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_auto_20210521_1721'),
        ('data', '0019_auto_20210522_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting'),
        ),
    ]
