# Generated by Django 3.1.7 on 2021-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20210522_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=25, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='beard_price',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hair_price',
        ),
    ]
