# Generated by Django 3.1.7 on 2021-05-25 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210521_1716'),
        ('data', '0022_auto_20210523_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='work_time',
        ),
        migrations.AddField(
            model_name='service',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.barber'),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
            preserve_default=False,
        ),
    ]
