# Generated by Django 3.1.7 on 2021-05-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20210525_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
