# Generated by Django 3.1.7 on 2021-05-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210521_1716'),
        ('data', '0024_auto_20210525_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='service',
            name='time',
        ),
        migrations.AddField(
            model_name='service',
            name='barbers',
            field=models.ManyToManyField(blank=True, related_name='services', to='accounts.Barber'),
        ),
        migrations.AddField(
            model_name='service',
            name='choosen_times',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
