# Generated by Django 3.1.7 on 2021-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20210525_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
