# Generated by Django 3.1.7 on 2021-05-31 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0027_auto_20210531_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='barbers',
            field=models.ManyToManyField(blank=True, related_name='service_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='vat',
            field=models.PositiveSmallIntegerField(choices=[(23, '23%'), (8, '8%'), (5, '5%'), (0, '0%')], default=0),
        ),
    ]
