# Generated by Django 3.1.7 on 2021-06-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210527_1240'),
        ('data', '0029_auto_20210601_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicegroup',
            options={},
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='barbers',
            field=models.ManyToManyField(blank=True, related_name='service_groups', to='accounts.Barber'),
        ),
    ]
