# Generated by Django 3.1.7 on 2021-06-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210527_1240'),
        ('data', '0030_auto_20210607_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroup',
            name='barbers',
            field=models.ManyToManyField(related_name='service_groups', to='accounts.Barber'),
        ),
        migrations.AlterUniqueTogether(
            name='servicegroup',
            unique_together=set(),
        ),
    ]
