# Generated by Django 3.1.7 on 2021-06-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210527_1240'),
        ('data', '0031_auto_20210607_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBarber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(default=0)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_barber_data', to='accounts.barber')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_barber_data', to='data.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='barbers',
            field=models.ManyToManyField(related_name='services', through='data.ServiceBarber', to='accounts.Barber'),
        ),
    ]
