# Generated by Django 3.1.7 on 2021-06-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210527_1240'),
        ('data', '0032_auto_20210607_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='private_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='public_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicebarber',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_barber_data', to='accounts.barber'),
        ),
        migrations.AlterField(
            model_name='servicebarber',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_barber_data', to='data.service'),
        ),
    ]
