# Generated by Django 3.1.7 on 2021-06-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_auto_20210624_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresources',
            name='resources',
            field=models.ManyToManyField(related_name='service_data', to='data.Resource'),
        ),
        migrations.AlterField(
            model_name='serviceresources',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_data', to='data.service'),
        ),
    ]
