# Generated by Django 3.1.7 on 2021-06-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_auto_20210625_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='calendar_step',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='data',
            name='calendar_timeslots',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='data',
            name='free_cancel_hours',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
